<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Anyi Wang" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.70.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          January 1, 0001
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>A knitted R Markdown document (as a PDF) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on 5/1/2020. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). Knit an html copy too, for later! In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(…) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)!</p>
<p>Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in your final project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is acceptable, as long as you understand what the warnings mean).</p>
</div>
<div id="find-data" class="section level2">
<h2>Find data:</h2>
<p>Find one dataset with at least 5 variables that wish to use to build models. At least one should be categorical (with 2-5 groups) and at least two should be numeric. Ideally, one of your variables will be binary (if not, you will need to create one by discretizing a numeric, which is workable but less than ideal). You will need a minimum of 40 observations (<em>at least</em> 10 observations for every explanatory variable you have, ideally 20+ observations/variable).</p>
<p>It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, you could also diversify your portfolio a bit by choosing a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.</p>
<p>Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
</div>
<div id="guidelines-and-rubric" class="section level2">
<h2>Guidelines and Rubric</h2>
<ul>
<li><strong>0. (5 pts)</strong> Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?</li>
</ul>
<p><em>My dataset, Summer, is derived from the Storms dataset, which included the positions and attributes of 198 tropical storms in the Atlantic Ocean, measured every six hours during the lifetime of a storm. The Summer dataset has omitted all NAs and filtered for only the summer months: June, July and August. It also has an added variable named “Binary,” derived from the original status variable, where “1” is a hurricane and “0” is not a hurricane, either tropical depression or tropical storm. The main numeric variables we’re using are wind speed (knots), air pressure (millibars), diameter of the area experiencing, and diameter of the area experiencing hurricane strength winds (64 knots or above). The categorical variable used is the month the storm occurs. The Summer dataset has 1203 observations in total.</em></p>
<ul>
<li><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all doesn’t make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss assumptions and whether or not they are likely to have been met (2).</li>
</ul>
<pre class="r"><code>library(dplyr)
library(tidyverse)
data &lt;- storms%&gt;%na.omit%&gt;%glimpse()</code></pre>
<pre><code>## Observations: 3,482
## Variables: 13
## $ name &lt;chr&gt; &quot;Alex&quot;, &quot;Alex&quot;, &quot;Alex&quot;, &quot;Alex&quot;, &quot;Alex&quot;,
&quot;Alex&quot;, &quot;Alex&quot;, &quot;Alex&quot;, &quot;Alex&quot;, &quot;Al...
## $ year &lt;dbl&gt; 2004, 2004, 2004, 2004, 2004, 2004, 2004,
2004, 2004, 2004, 2004, 2004, 200...
## $ month &lt;dbl&gt; 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, ...
## $ day &lt;int&gt; 31, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4,
4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 3,...
## $ hour &lt;dbl&gt; 18, 0, 6, 12, 18, 0, 6, 12, 18, 0, 6, 12,
18, 0, 6, 12, 18, 0, 6, 12, 18, 0...
## $ lat &lt;dbl&gt; 30.3, 31.0, 31.5, 31.6, 31.6, 31.5, 31.4,
31.3, 31.8, 32.4, 33.0, 34.2, 35....
## $ long &lt;dbl&gt; -78.3, -78.8, -79.0, -79.1, -79.2, -79.3,
-79.4, -79.0, -78.7, -78.2, -77.4...
## $ status &lt;chr&gt; &quot;tropical depression&quot;, &quot;tropical
depression&quot;, &quot;tropical depression&quot;, &quot;tropi...
## $ category &lt;ord&gt; -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 1, 2,
2, 1, 1, 2, 2, 3, 3, 3, 2, 1, 1, 0,...
## $ wind &lt;int&gt; 25, 25, 25, 30, 35, 35, 40, 50, 50, 60, 70,
85, 85, 80, 80, 85, 95, 105, 10...
## $ pressure &lt;int&gt; 1010, 1009, 1009, 1009, 1009, 1007,
1005, 992, 993, 987, 983, 974, 972, 974...
## $ ts_diameter &lt;dbl&gt; 0.0000, 0.0000, 0.0000, 0.0000,
57.5390, 57.5390, 172.6170, 155.3553, 143.8...
## $ hu_diameter &lt;dbl&gt; 0.0000, 0.0000, 0.0000, 0.0000,
0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0...</code></pre>
<pre class="r"><code>data1 &lt;- transform(data, lat = as.character(lat),long = as.character(long))
mydata&lt;-data1%&gt;% unite(name, year, day, hour, col = &quot;unique&quot;, sep=&quot;.&quot;)
Table1 &lt;- mydata%&gt;%select(unique, month, lat, long)
Table2 &lt;- mydata%&gt;%select(unique, status, category, wind, pressure, ts_diameter, hu_diameter)
finaldata &lt;- full_join(Table1, Table2, by= &quot;unique&quot;)
finaldata &lt;- transform(finaldata, month = as.character(month))
summer &lt;- finaldata%&gt;%filter(month %in% c(&quot;6&quot;, &quot;7&quot;, &quot;8&quot;))
summer &lt;-summer%&gt;%mutate(Binary=ifelse(status==&quot;hurricane&quot;,1,0))
summer &lt;-summer%&gt;%mutate(outcome=ifelse(status==&quot;hurricane&quot;,&quot;hurricane&quot;,&quot;not hurricane&quot;))
summer$outcome&lt;-factor(summer$outcome)
summer &lt;- summer %&gt;% select(-lat, -long, -category)
head(summer)</code></pre>
<pre><code>## unique month status wind pressure ts_diameter
hu_diameter Binary
## 1 Alex.2004.31.18 7 tropical depression 25 1010 0.000 0
0
## 2 Alex.2004.1.0 8 tropical depression 25 1009 0.000 0 0
## 3 Alex.2004.1.6 8 tropical depression 25 1009 0.000 0 0
## 4 Alex.2004.1.12 8 tropical depression 30 1009 0.000 0 0
## 5 Alex.2004.1.18 8 tropical storm 35 1009 57.539 0 0
## 6 Alex.2004.2.0 8 tropical storm 35 1007 57.539 0 0
## outcome
## 1 not hurricane
## 2 not hurricane
## 3 not hurricane
## 4 not hurricane
## 5 not hurricane
## 6 not hurricane</code></pre>
<pre class="r"><code>#Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all doesn&#39;t make sense) show a mean difference across levels of one of your categorical variables (3)

man1&lt;-manova(cbind(wind,pressure)~month, data=summer)
summary(man1)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## month 2 0.062054 19.212 4 2400 1.434e-15 ***
## Residuals 1200
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p><em>I performed MANOVA testing on whether wind or pressure (numeric variables) show a mean difference across the different summer months (categorical variable) of my dataset, resulting in a p-value of 1.434e-15, which is significant.</em></p>
<pre class="r"><code>#perform univariate ANOVAs to find response(s) showing a mean difference across groups (3)

summary.aov(man1)</code></pre>
<pre><code>## Response wind :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## month 2 8341 4170.4 7.3944 0.0006431 ***
## Residuals 1200 676799 564.0
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response pressure :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## month 2 2645 1322.27 3.9545 0.01942 *
## Residuals 1200 401244 334.37
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p><em>I performed univariate ANOVAs to find the response(s) showing a mean difference across groups, which was both wind and pressure, as their p-values was less than 0.05.</em></p>
<pre class="r"><code>#perform post-hoc t tests to find which groups differ

summer%&gt;%group_by(month)%&gt;%summarize(mean(wind),mean(pressure), mean(Binary))</code></pre>
<pre><code>## # A tibble: 3 x 4
##   month `mean(wind)` `mean(pressure)` `mean(Binary)`
##   &lt;chr&gt;        &lt;dbl&gt;            &lt;dbl&gt;          &lt;dbl&gt;
## 1 6             42.8             997.         0.0684
## 2 7             50.0             997.         0.179 
## 3 8             51.7             994.         0.245</code></pre>
<pre class="r"><code>pairwise.t.test(summer$wind, summer$month, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  summer$wind and summer$month 
## 
##   6       7      
## 7 0.00773 -      
## 8 0.00014 0.32081
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(summer$pressure, summer$month, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  summer$pressure and summer$month 
## 
##   6     7    
## 7 0.851 -    
## 8 0.095 0.013
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(summer$Binary, summer$month, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  summer$Binary and summer$month 
## 
##   6       7    
## 7 0.017   -    
## 8 1.2e-05 0.030
## 
## P value adjustment method: none</code></pre>
<p><em>Based on the post-hoc t tests, the differences in wind speed in June compared to July and August are significantly different. None of the differences in pressure between different months were significantly different.</em></p>
<pre class="r"><code>#Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3)

1-0.95^9 #Probability for making type I error (0.3697506)</code></pre>
<pre><code>## [1] 0.3697506</code></pre>
<pre class="r"><code>0.05/9 #Bonferroni Adjustment = 0.005555556</code></pre>
<pre><code>## [1] 0.005555556</code></pre>
<p><em>I performed 9 tests, and the probability of at least one type I error if unadjusted is 0.37. The bonferroni correction results in an alpha of 0.005555556, so only the difference in wind speed between June and August is significantly independent.</em></p>
<pre class="r"><code>#Briefly discuss assumptions and whether or not they are likely to have been met (2).

ggplot(summer, aes(x = wind, y = pressure)) +
geom_point(alpha = .5) + geom_density_2d(h=20) + coord_fixed() + facet_wrap(~month)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>covmats&lt;-summer%&gt;%group_by(status)%&gt;%do(covs=cov(.[7:8]))
for(i in 1:3){print(as.character(covmats$status[i])); print(covmats$covs[i])}</code></pre>
<pre><code>## [1] &quot;hurricane&quot;
## [[1]]
##             hu_diameter Binary
## hu_diameter    1391.465      0
## Binary            0.000      0
## 
## [1] &quot;tropical depression&quot;
## [[1]]
##             hu_diameter Binary
## hu_diameter           0      0
## Binary                0      0
## 
## [1] &quot;tropical storm&quot;
## [[1]]
##             hu_diameter Binary
## hu_diameter    7.042039      0
## Binary         0.000000      0</code></pre>
<p><em>The assumption of multivariate normality is not met as the graphs aren’t quite ovoid. Covariance matrices for each group also differs so the assumption of homogeneity of (co)variances was also not met. MANOVA analysis would not be the proper technique in this situation, but we’ll still continue through this project.</em></p>
<ul>
<li><strong>2. (10 pts)</strong> Perform some kind of randomization test on your data (that makes sense). This can be anything you want! State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</li>
</ul>
<pre class="r"><code>summer &lt;- summer%&gt;%mutate(hurricane_status=ifelse(status==&quot;hurricane&quot;,&quot;hurricane&quot;,&quot;not hurricane&quot;))

summer%&gt;%group_by(hurricane_status)%&gt;%summarize(means=mean(wind))%&gt;%summarize(diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `diff(means)`
##           &lt;dbl&gt;
## 1         -48.5</code></pre>
<pre class="r"><code>rand_dist&lt;-vector() 
  for(i in 1:5000){
    new &lt;- data.frame(wind=sample(summer$wind),storm =summer$hurricane_status)
    rand_dist[i] &lt;- mean(new[new$storm==&quot;not hurricane&quot;,]$wind)- mean(new[new$storm==&quot;hurricane&quot;,]$wind)}

t.test(data=summer, wind~hurricane_status)</code></pre>
<pre><code>##
## Welch Two Sample t-test
##
## data: wind by hurricane_status
## t = 35.566, df = 288.57, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not
equal to 0
## 95 percent confidence interval:
## 45.77518 51.13839
## sample estimates:
## mean in group hurricane mean in group not hurricane
## 88.55212 40.09534</code></pre>
<p><em>The null hypothesis is that wind speed has no effect on the status of a storm, whether or not it’s a hurricane. The alternative hypothesis is that wind speed has an effect on the status of a storm. Based on the results of the randomization test, the p-value was &lt; 2.2e-16, so we can reject the null hypothesis that wind speed has no effect on the status of a storm.</em></p>
<pre class="r"><code>#Create a plot visualizing the null distribution and the test statistic (3).

{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;, xlim = c(-50,8)); abline(v = -48.45678,col=&quot;red&quot;)}</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-8-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>mean(rand_dist&gt;48.45678 | rand_dist&lt; -48.45678) </code></pre>
<pre><code>## [1] 0</code></pre>
<ul>
<li><strong>3. (35 pts)</strong> Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.</li>
</ul>
<pre class="r"><code>#Interpret the coefficient estimates (do not discuss significance) (10)

summer$wind_c &lt;- summer$wind - mean(summer$wind)
summer$pres_c &lt;- summer$pressure - mean(summer$pressure)
summer %&gt;% count(status)</code></pre>
<pre><code>## # A tibble: 3 x 2
##   status                  n
##   &lt;chr&gt;               &lt;int&gt;
## 1 hurricane             259
## 2 tropical depression   267
## 3 tropical storm        677</code></pre>
<pre class="r"><code>fit &lt;- lm(wind~status*pres_c, data=summer)
summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = wind ~ status * pres_c, data = summer)
##
## Residuals:
## Min 1Q Median 3Q Max
## -26.601 -3.408 1.195 2.949 24.299
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 60.32980 0.70504 85.569 &lt; 2e-16 ***
## statustropical depression -31.63135 1.41562 -22.345 &lt;
2e-16 ***
## statustropical storm -11.19614 0.77449 -14.456 &lt; 2e-16
***
## pres_c -0.99375 0.02065 -48.134 &lt; 2e-16 ***
## statustropical depression:pres_c 0.97213 0.09507 10.225
&lt; 2e-16 ***
## statustropical storm:pres_c 0.24336 0.04109 5.923
4.13e-09 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 6.301 on 1197 degrees of
freedom
## Multiple R-squared: 0.9306, Adjusted R-squared: 0.9303
## F-statistic: 3212 on 5 and 1197 DF, p-value: &lt; 2.2e-16</code></pre>
<p><em>The intercept shows the wind speed when the pressure is at the mean value and the status of the storm is a hurricane. The coefficient estimates of statustropical depression and statustropical storm show the decrease in wind speed when the pressure remains at the mean value, but the status of the storm changes to tropical depression and storm. The pres_c coefficient estimate represents the slope of the reference group, hurricanes. The statustropical depression:pres_c and statustropical storm:pres_c coefficient estimates show the difference in slopes when the status of the storm changes to tropical depression and storm.</em></p>
<pre class="r"><code>#Plot the regression using `ggplot()`. If your interaction is numeric by numeric, refer to code near the end of WS15 to make the plot. If you have 3 or more predictors, just chose two to plot for convenience. (8) and check assumptions of linearity

ggplot(summer, aes(x=pres_c, y= wind))+geom_point(aes(color=factor(status)))+  stat_smooth(method=&quot;lm&quot;,se=F,fullrange=T)+ theme(legend.position=c(.9,.19))</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-10-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#This plot shows the linearity between the predictor (centered pressure) and the response variable (wind), and it&#39;s fairly linear</code></pre>
<pre class="r"><code>#Check assumptions of normality and homoskedasticity either graphically or using a hypothesis test (4)

#Test for homoskedasticity
resids&lt;-fit$residuals; fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, col=&quot;red&quot;)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-11-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#The homoskedacity is okay because there is no flaring in the graph.

#Normality test
plot(fit,2) </code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-11-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code># There&#39;s some flaring at the ends, so normality may have not been met.</code></pre>
<pre class="r"><code>library(lmtest)
library(sandwich)
coeftest(fit, vcov=vcovHC(fit))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 60.329796 0.863161 69.8940 &lt; 2.2e-16 ***
## statustropical depression -31.631352 1.036442 -30.5192 &lt;
2.2e-16 ***
## statustropical storm -11.196143 0.943123 -11.8713 &lt;
2.2e-16 ***
## pres_c -0.993752 0.031681 -31.3678 &lt; 2.2e-16 ***
## statustropical depression:pres_c 0.972134 0.052449
18.5350 &lt; 2.2e-16 ***
## statustropical storm:pres_c 0.243364 0.054788 4.4419
9.74e-06 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = wind ~ status * pres_c, data = summer)
##
## Residuals:
## Min 1Q Median 3Q Max
## -26.601 -3.408 1.195 2.949 24.299
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 60.32980 0.70504 85.569 &lt; 2e-16 ***
## statustropical depression -31.63135 1.41562 -22.345 &lt;
2e-16 ***
## statustropical storm -11.19614 0.77449 -14.456 &lt; 2e-16
***
## pres_c -0.99375 0.02065 -48.134 &lt; 2e-16 ***
## statustropical depression:pres_c 0.97213 0.09507 10.225
&lt; 2e-16 ***
## statustropical storm:pres_c 0.24336 0.04109 5.923
4.13e-09 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 6.301 on 1197 degrees of
freedom
## Multiple R-squared: 0.9306, Adjusted R-squared: 0.9303
## F-statistic: 3212 on 5 and 1197 DF, p-value: &lt; 2.2e-16</code></pre>
<p><em>The coefficient estimates didn’t change after robust SEs. The standard errors changed by less than 0.3, which isn’t significant. The adjusted R^2 shows that 0.9306 of the variation in the outcome is explained by my model.</em></p>
<pre><code>- Interpret the coefficient estimates (do not discuss significance) (10)
- Plot the regression using `ggplot()`. If your interaction is numeric by numeric, refer to code near the end of WS15 to make the plot. If you have 3 or more predictors, just chose two to plot for convenience. (8)
- Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (4)
- Regardless, recompute regression results with robust standard errors via `coeftest(..., vcov=vcovHC(...))`. Discuss significance of results, including any changes from before/after robust SEs if applicable. (8)
- What proportion of the variation in the outcome does your model explain? (4)</code></pre>
<ul>
<li><strong>4. (5 pts)</strong> Rerun same regression model (with interaction), but this time compute bootstrapped standard errors. Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</li>
</ul>
<pre class="r"><code>fit &lt;- lm(wind~status*pres_c, data=summer)

samp_distn&lt;-replicate(5000, {
  boot_dat&lt;-summer[sample(nrow(summer),replace=TRUE),]
  fit&lt;-lm(wind~status*pres_c, data=boot_dat) 
  coef(fit)
})

summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = wind ~ status * pres_c, data = summer)
##
## Residuals:
## Min 1Q Median 3Q Max
## -26.601 -3.408 1.195 2.949 24.299
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 60.32980 0.70504 85.569 &lt; 2e-16 ***
## statustropical depression -31.63135 1.41562 -22.345 &lt;
2e-16 ***
## statustropical storm -11.19614 0.77449 -14.456 &lt; 2e-16
***
## pres_c -0.99375 0.02065 -48.134 &lt; 2e-16 ***
## statustropical depression:pres_c 0.97213 0.09507 10.225
&lt; 2e-16 ***
## statustropical storm:pres_c 0.24336 0.04109 5.923
4.13e-09 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 6.301 on 1197 degrees of
freedom
## Multiple R-squared: 0.9306, Adjusted R-squared: 0.9303
## F-statistic: 3212 on 5 and 1197 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>coeftest(fit, vcov=vcovHC(fit))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 60.329796 0.863161 69.8940 &lt; 2.2e-16 ***
## statustropical depression -31.631352 1.036442 -30.5192 &lt;
2.2e-16 ***
## statustropical storm -11.196143 0.943123 -11.8713 &lt;
2.2e-16 ***
## pres_c -0.993752 0.031681 -31.3678 &lt; 2.2e-16 ***
## statustropical depression:pres_c 0.972134 0.052449
18.5350 &lt; 2.2e-16 ***
## statustropical storm:pres_c 0.243364 0.054788 4.4419
9.74e-06 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>## (Intercept) statustropical depression statustropical
storm pres_c
## 1 0.8673102 1.047537 0.9435167 0.03184516
## statustropical depression:pres_c statustropical
storm:pres_c
## 1 0.0529255 0.05404471</code></pre>
<p><em>The bootstrapped standard errors are closer to the robust SEs than the original SEs, but the differences are very minor. Therefore, the p-values didn’t change very much, but the p-value of statustropical storm:pres_c was higher in the robust SEs than the original, so it’s probably also higher in the bootstrapped standard errors. When standard error increases, the p-value also increases, as the finding are less significant when there’s a larger margin for error.</em></p>
<ul>
<li><strong>5. (40 pts)</strong> Perform a logistic regression predicting a binary categorical variable (if you don’t have one, make/get one) from at least two explanatory variables (interaction not necessary).</li>
</ul>
<pre class="r"><code>#Interpret coefficient estimates in context (10)
fit&lt;-glm(Binary~ ts_diameter+hu_diameter,data=summer,family=&quot;binomial&quot;)
coeftest(fit)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -5.55308582 0.74812479 -7.4227 1.148e-13 ***
## ts_diameter -0.00056191 0.00593289 -0.0947 0.9245
## hu_diameter 0.37219840 0.04599570 8.0920 5.868e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coeftest(fit))</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##              Estimate Std. Error   z value Pr(&gt;|z|)
## (Intercept) 0.0038755  2.1130339    0.0006    1.000
## ts_diameter 0.9994383  1.0059505    0.9096    2.521
## hu_diameter 1.4509208  1.0470699 3268.3052    1.000</code></pre>
<p><em>The odds of a storm being a hurricane is 0.0038755 when the diameter of the area experiencing tropical storm strength winds (34 knots or above) and the diameter of the area experiencing hurricane strength winds (64 knots or above) are both zero. While negative odds don’t usually make sense, the coefficient estimate means that a storm will definitely not be a hurricane when ts_diameter and hu_diameter, which is understandable. When controlling for hu_diameter, the odds of a storm being a hurricane increases by 0.9994383</em></p>
<pre class="r"><code>#Report a confusion matrix for your logistic regression (2)
probs&lt;-predict(fit,type=&quot;response&quot;)
table(predict=as.numeric(probs&gt;.5),truth=summer$Binary)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict    0    1  Sum
##     0    943    3  946
##     1      1  256  257
##     Sum  944  259 1203</code></pre>
<pre class="r"><code>#Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), and Recall (PPV) of your model (5)

#Accuracy
(943+256)/1203</code></pre>
<pre><code>## [1] 0.996675</code></pre>
<pre class="r"><code>#ratio of the correctly labeled storms to total amount of storms - the number of True Positives for classifying storms as hurricanes out of all the data. Very high accuracy.

#Sensitivity (TPR)
256/259</code></pre>
<pre><code>## [1] 0.988417</code></pre>
<pre class="r"><code>#proportion of true positives that were correctly identified as that --&gt; out of all 259 actual hurricanes, 256 of those storms were identified as hurricanes. The TPR was quite high, indicating this prediction is pretty accurate.

#Specificity (TNR)
943/944  </code></pre>
<pre><code>## [1] 0.9989407</code></pre>
<pre class="r"><code>#proportion of true negatives that are correctly identified as that --&gt; Out of 944 actual storms that weren&#39;t hurricanes, 943 of those storms were properly identified as not hurricanes. The TNR was also quite high, indicating that our model was pretty accurate for this prediction

#Recall (PPV)
256/257</code></pre>
<pre><code>## [1] 0.9961089</code></pre>
<pre class="r"><code>#the number of relevant reports identified divided by the total number of reports identified --&gt; out of all 257 storms identified as hurricanes, 256 were actually hurricanes. The PPV was pretty high, good prediction model</code></pre>
<pre class="r"><code>#Using ggplot, plot density of log-odds (logit) by your binary outcome variable (3)
summer$logit&lt;-predict(fit,type=&quot;link&quot;)
summer%&gt;%ggplot()+geom_density(aes(logit,color=outcome,fill=outcome), alpha=.4)+xlim(-12,8)+ylim(0,0.2)+theme(legend.position=c(.85,.85))+geom_vline(xintercept=-10)+xlab(&quot;logit (log-odds)&quot;)+geom_rug(aes(logit,color=outcome))+ geom_text(x=-5,y=.07,label=&quot;TN = 943&quot;)+
  geom_text(x=-1.75,y=.008,label=&quot;FN = 3&quot;)+
  geom_text(x=1,y=.006,label=&quot;FP = 1&quot;)+
  geom_text(x=5,y=.04,label=&quot;TP = 256&quot;)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-17-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (10)
library(plotROC)
library(pROC)
ROCplot&lt;-ggplot(summer)+geom_roc(aes(d=Binary,m=probs), n.cuts=0) 
ROCplot</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-18-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.9993824</code></pre>
<pre class="r"><code>class_diag(probs,summer$Binary)</code></pre>
<pre><code>##        acc     sens      spec       ppv       auc
## 1 0.996675 0.988417 0.9989407 0.9961089 0.9993824</code></pre>
<pre class="r"><code>auc(summer$outcome,probs)</code></pre>
<pre><code>## Area under the curve: 0.9994</code></pre>
<p><em>With an AUC of 0.9994, these variables are great predictors for the response variable, whether the storm is a hurricane or not. This is a very accurate prediction model.</em></p>
<pre class="r"><code>#Perform 10-fold (or repeated random sub-sampling) CV and report average out-of-sample Accuracy, Sensitivity, and Recall(10)
k=10 
data&lt;-summer[sample(nrow(summer)),] #randomly order rows
folds&lt;-cut(seq(1:nrow(data)),breaks=k,labels=F) # create folds

diags&lt;-NULL
for(i in 1:k){
  train&lt;-data[folds!=i,] 
  test&lt;-data[folds==i,]
  truth&lt;-test$Binary
  fit&lt;-glm(Binary~ ts_diameter+hu_diameter,data=train,family=&quot;binomial&quot;)
  probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
  diags&lt;-rbind(diags,class_diag(probs,truth))
}
summarize_all(diags,mean)</code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.9966736 0.9875824 0.9989011 0.9966667 0.9994505</code></pre>
<p><em>The average out-of-sample Accuracy, Sensitivity, and Recall are 0.9966804, 0.9869091, and 0.9964286.</em></p>
<pre><code>- Interpret coefficient estimates in context (10)
- Report a confusion matrix for your logistic regression (2)
- Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), and Recall (PPV) of your model (5)
- Using ggplot, plot density of log-odds (logit) by your binary outcome variable (3)
- Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (10)
- Perform 10-fold (or repeated random sub-sampling) CV and report average out-of-sample Accuracy, Sensitivity, and Recall (10)</code></pre>
<ul>
<li><strong>6. (10 pts)</strong> Choose one variable you want to predict (can be one you used from before; either binary or continuous) and run a LASSO regression inputting all the rest of your variables as predictors. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., <code>lambda.1se</code>). Discuss which variables are retained. Perform 10-fold CV using this model: if response in binary, compare model’s out-of-sample accuracy to that of your logistic regression in part 5; if response is numeric, compare the residual standard error (at the bottom of the summary output, aka RMSE): lower is better fit!</li>
</ul>
<pre class="r"><code>library(glmnet)
lasso &lt;- summer %&gt;% select(-unique, -outcome, -hurricane_status, -wind_c, -pres_c, -logit, -status)
lasso &lt;- lasso %&gt;% mutate(month=factor(month))
y &lt;- as.matrix(lasso$Binary)
x&lt;-model.matrix(Binary~-1+.,data=lasso)

cv&lt;-cv.glmnet(x,y,family=&quot;binomial&quot;)
regression&lt;-glmnet(x,y,family=&quot;binomial&quot;,lambda=cv$lambda.1se)
coef(regression)</code></pre>
<pre><code>## 8 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                      s0
## (Intercept) -12.4203098
## month6        .        
## month7        .        
## month8        .        
## wind          0.1650436
## pressure      .        
## ts_diameter   .        
## hu_diameter   0.0974916</code></pre>
<p><em>The variables wind and hu_diameter were retained after the lasso test.</em></p>
<pre class="r"><code>k=10
data&lt;-lasso[sample(nrow(lasso)),]
folds&lt;-cut(seq(1:nrow(lasso)),breaks=k,labels=F)

diags&lt;-NULL
for(i in 1:k){
  train &lt;- data[folds!=i,] #create training set (all but fold i)
  test &lt;- data[folds==i,] #create test set (just fold i)
  truth &lt;- test$Binary #save truth labels from fold i
  
  fit &lt;- glm(Binary~wind+hu_diameter, 
             data=train, family=&quot;binomial&quot;)
  probs &lt;- predict(fit, newdata=test, type=&quot;response&quot;)
  
  diags&lt;-rbind(diags,class_diag(probs,truth))
}

diags%&gt;%summarize_all(mean)</code></pre>
<pre><code>##         acc sens      spec       ppv       auc
## 1 0.9991667    1 0.9989362 0.9962963 0.9994681</code></pre>
<p><em>The out-of-sample accuracy is now 0.9991667, compared to 0.9966804 from the logistic regression in part 5. While this is ever so slightly more accurate, this dataset had some great predictors of the response variable. This increase in out-of-sample accuracy is very small, nearly negligable.</em></p>
</div>
<div id="where-do-i-find-data-again" class="section level2">
<h2>Where do I find data again?</h2>
<p>You can choose ANY datasets you want that meet the above criteria for variables and observations. You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat, or whatever. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn’t end up being that big of a deal.</p>
<p>If you are totally clueless and have no direction at all, log into the server and type</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))</code></pre>
<p>This will print out a list of <strong>ALL datasets in ALL packages</strong> installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much… To start with something more manageable, just run the command on your own computer, or just run <code>data()</code> to bring up the datasets in your current environment. To read more about a dataset, do <code>?packagename::datasetname</code>.</p>
<p>If it is easier for you, and in case you don’t have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
<ul>
<li><p>A good package to download for fun/relevant data is <code>fivethiryeight</code>.
Run <code>install.packages("fivethirtyeight"),</code> load the packages with <code>library(fivethirtyeight)</code>, run <code>data()</code>, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.</p></li>
<li><p>If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above</p></li>
<li><p>However, you <em>emphatically DO NOT</em> have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: <a href="https://www.wunderground.com/history/" class="uri">https://www.wunderground.com/history/</a>). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!</p></li>
<li><p>Here is a curated list of interesting datasets (read-only spreadsheet format): <a href="https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit" class="uri">https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit</a></p></li>
<li><p>Here is another great compilation of datasets: <a href="https://github.com/rfordatascience/tidytuesday" class="uri">https://github.com/rfordatascience/tidytuesday</a></p></li>
<li><p>Here is the UCI Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<ul>
<li>See also <a href="https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data" class="uri">https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data</a></li>
</ul></li>
<li><p>Here is another good general place to look: <a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></p></li>
<li><p>To help narrow your search down or to see interesting variable ideas, check out <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!</p></li>
<li><p>If you are interested in medical data, check out www.countyhealthrankings.org</p></li>
<li><p>If you are interested in scraping UT data, they make <em>loads</em> of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: <a href="https://reports.utexas.edu/statistical-handbook" class="uri">https://reports.utexas.edu/statistical-handbook</a></p></li>
</ul>
<div id="broader-data-sources" class="section level5">
<h5>Broader data sources:</h5>
<p><a href="www.data.gov">Data.gov</a> 186,000+ datasets!</p>
<p><a href="Social%20Explorer">Social Explorer</a> is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.</p>
<p><a href="www.bls.gov">U.S. Bureau of Labor Statistics</a></p>
<p><a href="www.census.gov">U.S. Census Bureau</a></p>
<p><a href="www.gapminder.org/data">Gapminder</a>, data about the world.</p>
<p>…</p>
</div>
</div>
</div>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
